"""Initial database

Revision ID: 564c04e18b0b
Revises: 
Create Date: 2019-03-17 19:49:58.235517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564c04e18b0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('discriminator', sa.BigInteger(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dm_channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('remote_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['remote_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guilds',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.String(length=2000), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_edits',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('edit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('discriminator', sa.BigInteger(), nullable=False),
    sa.Column('avatar', sa.String(length=2000), nullable=False),
    sa.Column('edit_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('edit_id')
    )
    op.create_table('dm_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=True),
    sa.Column('embed', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['dm_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guild_channels',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guild_edits',
    sa.Column('edit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('edit_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('edit_id')
    )
    op.create_table('guild_members',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'guild_id', 'id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ban_audit',
    sa.Column('audit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('member_was_banned', sa.Boolean(), nullable=False),
    sa.Column('event_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['guild_members.id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('dm_channel_pins',
    sa.Column('pin_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dm_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(), nullable=False),
    sa.Column('unpinned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dm_channel_id'], ['dm_channels.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['dm_messages.id'], ),
    sa.PrimaryKeyConstraint('pin_id')
    )
    op.create_table('dm_message_attachments',
    sa.Column('attachment_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('filesize', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['dm_messages.id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('dm_message_deletions',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('deletion_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['dm_messages.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('dm_message_edits',
    sa.Column('edit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=True),
    sa.Column('embed', sa.JSON(), nullable=True),
    sa.Column('edit_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['dm_messages.id'], ),
    sa.PrimaryKeyConstraint('edit_id')
    )
    op.create_table('guild_channel_edits',
    sa.Column('edit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=1024), nullable=True),
    sa.Column('edit_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guild_channel_id'], ['guild_channels.id'], ),
    sa.PrimaryKeyConstraint('edit_id')
    )
    op.create_table('guild_join_guild_leave_audit',
    sa.Column('audit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('member_joined', sa.Boolean(), nullable=False),
    sa.Column('event_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['guild_members.id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('guild_member_edit',
    sa.Column('member_id', sa.BigInteger(), nullable=True),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('edit_time', sa.DateTime(), nullable=False),
    sa.Column('edit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['guild_members.id'], ),
    sa.PrimaryKeyConstraint('edit_id')
    )
    op.create_table('guild_member_roles',
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['guild_members.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'role_id')
    )
    op.create_table('guild_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=True),
    sa.Column('embed', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['guild_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_audit',
    sa.Column('audit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('role_was_added', sa.Boolean(), nullable=False),
    sa.Column('event_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['guild_members.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('role_edits',
    sa.Column('role_id', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('edit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('edit_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('edit_id')
    )
    op.create_table('guild_channel_pins',
    sa.Column('pin_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(), nullable=False),
    sa.Column('unpinned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guild_channel_id'], ['guild_channels.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['guild_messages.id'], ),
    sa.PrimaryKeyConstraint('pin_id')
    )
    op.create_table('guild_message_attachments',
    sa.Column('attachment_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('filesize', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['guild_messages.id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('guild_message_deletions',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('deletion_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['guild_messages.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('guild_message_edits',
    sa.Column('edit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=True),
    sa.Column('embed', sa.JSON(), nullable=True),
    sa.Column('edit_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['guild_messages.id'], ),
    sa.PrimaryKeyConstraint('edit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_message_edits')
    op.drop_table('guild_message_deletions')
    op.drop_table('guild_message_attachments')
    op.drop_table('guild_channel_pins')
    op.drop_table('role_edits')
    op.drop_table('role_audit')
    op.drop_table('guild_messages')
    op.drop_table('guild_member_roles')
    op.drop_table('guild_member_edit')
    op.drop_table('guild_join_guild_leave_audit')
    op.drop_table('guild_channel_edits')
    op.drop_table('dm_message_edits')
    op.drop_table('dm_message_deletions')
    op.drop_table('dm_message_attachments')
    op.drop_table('dm_channel_pins')
    op.drop_table('ban_audit')
    op.drop_table('roles')
    op.drop_table('guild_members')
    op.drop_table('guild_edits')
    op.drop_table('guild_channels')
    op.drop_table('dm_messages')
    op.drop_table('user_edits')
    op.drop_table('guilds')
    op.drop_table('dm_channels')
    op.drop_table('users')
    # ### end Alembic commands ###
