"""Make database aware if saved data is local

Revision ID: 6cdb53199fe9
Revises: d639ec95a221
Create Date: 2019-06-17 00:51:12.048514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cdb53199fe9'
down_revision = 'd639ec95a221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dm_message_attachments', sa.Column('localized_url', sa.Boolean(), nullable=False))
    op.add_column('guild_edits', sa.Column('localized_url', sa.Boolean(), nullable=False))
    op.add_column('guild_message_attachments', sa.Column('localized_url', sa.Boolean(), nullable=False))
    op.add_column('guilds', sa.Column('localized_url', sa.Boolean(), nullable=False))
    op.add_column('user_edits', sa.Column('localized_avatar', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('localized_avatar', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'localized_avatar')
    op.drop_column('user_edits', 'localized_avatar')
    op.drop_column('guilds', 'localized_url')
    op.drop_column('guild_message_attachments', 'localized_url')
    op.drop_column('guild_edits', 'localized_url')
    op.drop_column('dm_message_attachments', 'localized_url')
    # ### end Alembic commands ###
