"""Add icon_url to Edit table

Revision ID: d639ec95a221
Revises: 37af9542fb7e
Create Date: 2019-06-10 17:04:58.117754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd639ec95a221'
down_revision = '37af9542fb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_edits', sa.Column('icon_url', sa.String(length=2000), nullable=True))
    op.create_unique_constraint(None, 'guild_members', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guild_members', type_='unique')
    op.drop_column('guild_edits', 'icon_url')
    # ### end Alembic commands ###
